"""
extract_weights.py — Regenerate model_weights.js from a new .h5 model
=======================================================================
Run this whenever you retrain your model:

    python3 scripts/extract_weights.py

It reads models/asl_recognizer_model.h5 and writes src/utils/model_weights.js.

Requirements:
    pip install h5py numpy
"""

import os, sys, json
import numpy as np

try:
    import h5py
except ImportError:
    sys.exit("Missing h5py. Run: pip install h5py")

# ── Paths ──────────────────────────────────────────────────────
SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR    = os.path.dirname(SCRIPT_DIR)
MODEL_PATH  = os.path.join(ROOT_DIR, 'models', 'asl_recognizer_model.h5')
OUTPUT_PATH = os.path.join(ROOT_DIR, 'src', 'utils', 'model_weights.js')

if not os.path.exists(MODEL_PATH):
    sys.exit(f"Model not found at: {MODEL_PATH}")

print(f"Reading: {MODEL_PATH}")

with h5py.File(MODEL_PATH, 'r') as f:
    # ── Auto-detect weight keys ────────────────────────────────
    # Works for both old and new Keras h5 formats
    def find_weights(f, name):
        results = []
        def visitor(path, obj):
            if isinstance(obj, h5py.Dataset) and name in path:
                results.append((path, obj[:]))
        f['model_weights'].visititems(visitor)
        return results

    kernels = [v for _, v in sorted(find_weights(f, 'kernel'), key=lambda x: x[0])]
    biases  = [v for _, v in sorted(find_weights(f, 'bias'),   key=lambda x: x[0])]

# ── Filter out non-dense layers (dropout has no weights) ──────
# Dense layers only: we expect 3 pairs (W1,b1), (W2,b2), (W3,b3)
print(f"Found {len(kernels)} kernel layers, {len(biases)} bias layers")

if len(kernels) != 3:
    print("WARNING: Expected 3 dense layers. Check model architecture.")

W1, b1 = kernels[0], biases[0]
W2, b2 = kernels[1], biases[1]
W3, b3 = kernels[2], biases[2]

print(f"Layer 1: {W1.shape} → {b1.shape}")
print(f"Layer 2: {W2.shape} → {b2.shape}")
print(f"Layer 3: {W3.shape} → {b3.shape}")
print(f"Classes: {b3.shape[0]} (expected 27 = A–Z + SPACE)")

# ── Write JS ──────────────────────────────────────────────────
js = f"""/**
 * model_weights.js — Auto-generated by scripts/extract_weights.py
 * ================================================================
 * DO NOT EDIT MANUALLY.
 * Source: models/asl_recognizer_model.h5
 *
 * Architecture:
 *   Input:  {W1.shape[0]} features  (21 landmarks × x,y, wrist-normalised)
 *   Dense:  {W1.shape[0]} → {b1.shape[0]}, ReLU
 *   Dense:  {W2.shape[0]} → {b2.shape[0]}, ReLU
 *   Dense:  {W3.shape[0]} → {b3.shape[0]}, Softmax
 *   Output: {b3.shape[0]} classes (A–Z + SPACE)
 */

export const MODEL_W1 = {json.dumps(W1.tolist())};
export const MODEL_B1 = {json.dumps(b1.tolist())};
export const MODEL_W2 = {json.dumps(W2.tolist())};
export const MODEL_B2 = {json.dumps(b2.tolist())};
export const MODEL_W3 = {json.dumps(W3.tolist())};
export const MODEL_B3 = {json.dumps(b3.tolist())};
"""

with open(OUTPUT_PATH, 'w') as f:
    f.write(js)

size_kb = os.path.getsize(OUTPUT_PATH) / 1024
print(f"\n Written: {OUTPUT_PATH}  ({size_kb:.0f} KB)")
print("   Restart your dev server to apply changes.")



